name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: go tests
        run: go test -v -covermode=count -json ./... > test.json
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.6.0
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
      BATON_USERNAME: ${{ secrets.BATON_DOCKERHUB_USERNAME }}
      BATON_PASSWORD: ${{ secrets.BATON_DOCKERHUB_PASSWORD }}
      BATON_LOG_LEVEL: debug
      CONNECTOR_GRANT: 'team:698390:member:user:062cd47aa72c441e8c660c7273c780e3'
      CONNECTOR_ENTITLEMENT: 'team:698390:member'
      CONNECTOR_PRINCIPAL: '062cd47aa72c441e8c660c7273c780e3'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-dockerhub
        run: go build ./cmd/baton-dockerhub
      - name: Run baton-dockerhub
        run: ./baton-dockerhub

      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin

      - name: Sync and check resource/grant
        env:
          BATON_CONNECTOR: ./baton-dockerhub
          BATON: baton
        run: ./scripts/grant-revoke.sh
