name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_USERNAME: ${{ secrets.BATON_DOCKERHUB_USERNAME }}
      BATON_PASSWORD: ${{ secrets.BATON_DOCKERHUB_PASSWORD }}
      BATON_LOG_LEVEL: debug
      CONNECTOR_GRANT: 'team:698390:member:user:062cd47aa72c441e8c660c7273c780e3'
      CONNECTOR_ENTITLEMENT: 'team:698390:member'
      CONNECTOR_PRINCIPAL: '062cd47aa72c441e8c660c7273c780e3'
      CONNECTOR_PRINCIPAL_TYPE: 'user'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-dockerhub
        run: go build ./cmd/baton-dockerhub
      - name: Run baton-dockerhub
        run: ./baton-dockerhub
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Sync and check resource/grant
        env:
          BATON_CONNECTOR: ./baton-dockerhub
          BATON: baton
        run: ./scripts/grant-revoke.sh
